News read/write
ice-blockchain/husky pull request #2
Opened 2022-09-28 08:22 UTC by ice-laius

2022-09-28 09:18 UTC, ice-myles requested changes

2022-09-28 09:18 UTC, ice-myles commented on news/news_get.go
> +	err := r.db.GetTyped("NEWS", "pk_unnamed_NEWS_1", tarantool.StringKey{S: newsID}, result)
```
if err := r.db.GetTyped("NEWS", "pk_unnamed_NEWS_1", tarantool.StringKey{S: newsID}, result); err != nil {
    return nil, errors.Wrapf(err, "failed to get news by newsID:%v", newsID)}
}
if result.ID == "" {
	return nil, ErrNotFound
}

return result, nil
```
I would change this in this way, not to return not null pointer if error happens in the end.

2022-09-28 09:18 UTC, ice-myles commented on news/news_create.go
> +		//return errors.Wrapf(ErrInvalidNewsTitle, "unable to translate title: %v", title)
What is the sense of verifying if we will always return nil?

2022-09-28 09:18 UTC, ice-myles commented on cmd/husky-pack/contract.go
> -	userNotFoundErrorCode      = "USER_NOT_FOUND"
Let's restore all these codes. They will be needed for notifications.

2022-09-28 09:18 UTC, ice-myles commented on news/news_modify.go
> +	"github.com/ice-blockchain/wintr/connectors/storage"
`golangcgi-lint run` at least for the imports for each file.

2022-09-28 09:26 UTC, ice-ares commented on cmd/husky-pack/news.go
> +		ID:                   uuid.NewString(),
nope, do it inside news pckage

2022-09-28 09:27 UTC, ice-ares commented on cmd/husky-pack/news.go
> +			case errors.Is(err, users.ErrRaceCondition):
u need extra stuff for this to work, you need to return it in the response, add it in swagger. check eskimo

2022-09-28 10:30 UTC, ice-ares commented on news/news_create.go
> +		"id":                    news.ID,
set it in this method

2022-09-28 10:30 UTC, ice-ares commented on news/news_create.go
> +	if err = storage.CheckSQLDMLErr(r.db.PrepareExecute(sql, params)); err != nil {
error handling

2022-09-28 10:31 UTC, ice-ares commented on news/news_create.go
> +	if url == "" {
should never happen, so remove it

2022-09-28 10:31 UTC, ice-ares commented on news/news_create.go
> +	_, err := r.translationsClient.Translate(ctx, "en", title, nil)
remove the nil

2022-09-28 10:32 UTC, ice-ares commented on news/news_get.go
> +	var result []*PersonalNews
too far away

2022-09-28 10:33 UTC, ice-ares commented on news/news_get.go
> +	var result []*PersonalNews
and u can reuse the method result vars

2022-09-28 10:34 UTC, ice-ares commented on news/news_get.go
> +				COALESCE(CAST(v.created_at AS BOOLEAN), FALSE) AS viewed,
`v.created_at is null` or `v.created_at == null` is enough

2022-09-28 10:35 UTC, ice-ares commented on news/news_get.go
> +		return nil, errors.Wrapf(ErrNotFound, "no news found for type:%v", newsType)
nope, not found is only for get of 1. not get of list

2022-09-28 10:37 UTC, ice-ares commented on news/news_get.go
> +		news.Title = r.translate(ctx, language, news.Title)
since u already have to do this,  set the correct image url here as well, and replace all those columns in sql with n.*

2022-09-28 10:38 UTC, ice-ares commented on news/news_get.go
> +		return phrase
nope, just return error

2022-09-28 10:39 UTC, ice-ares commented on news/news_get.go
> +	err := r.db.GetTyped("NEWS", "pk_unnamed_NEWS_1", tarantool.StringKey{S: newsID}, result)
there's not gonna be a nil pointer, cuz of result := new(News)

2022-09-28 10:44 UTC, ice-ares commented on news/news_modify.go
> +	if err = storage.CheckSQLDMLErr(r.db.PrepareExecute(sql, params)); err != nil {
handle more errors

2022-09-28 10:45 UTC, ice-ares commented on news/news_modify.go
> +	return &PersonalNews{News: *oldNews}, nil
thats correct

2022-09-28 10:47 UTC, ice-ares commented on news/news_modify.go
> +		return nil, errors.Wrapf(err, "error inserting newsID %v/userID %v", newsID, userID)
hmm, in case of conflict, you should return `&PersonalNews{News: *oldNews, Viewed: true}, nil` Cuz people can view the news multiple times, but we count only the first, and we just no-op for the rest

2022-09-28 10:48 UTC, ice-ares commented on news/news_modify.go
> +		UserID:    requestingUserID(ctx),
pass that as arg. Use requestingUserID only in top level methods.

2022-09-28 10:50 UTC, ice-ares commented on news/news_modify.go
> +	sql := `UPDATE news SET views = views+1 WHERE id = :newsID`
myles is right.

2022-09-28 10:55 UTC, ice-ares commented on notifications/DDL.lua
> +                    user_id STRING NOT NULL REFERENCES users(id) ON DELETE CASCADE,
its user_id

2022-09-28 11:18 UTC, ice-laius commented on news/news_modify.go
> +	return &PersonalNews{News: *oldNews}, nil
i was thinking a lot about 'true' value..%)
oldNews.Views++

2022-09-28 11:27 UTC, ice-laius commented on news/news_modify.go
> +	sql := `UPDATE news SET views = views+1 WHERE id = :newsID`
// nosql in the views table, sql in news -- that's why ) 
done

2022-09-28 12:06 UTC, ice-ares commented on news/news_modify.go
> +	sql := `UPDATE news SET views = views+1 WHERE id = :newsID`
I know. I remember everything I  say. People change their minds sometimes. I do too.

2022-09-28 12:12 UTC, ice-ares commented on news/news_modify.go
> +	return &PersonalNews{News: *oldNews}, nil
I think he meant viewed. views should be unchanged

2022-09-28 12:17 UTC, ice-laius commented on news/contract.go
> +	newsViewedByUsers struct {
done

2022-09-28 12:19 UTC, ice-laius commented on news/news_create.go
> +		//return errors.Wrapf(ErrInvalidNewsTitle, "unable to translate title: %v", title)
done

2022-09-28 12:24 UTC, ice-laius commented on news/news_create.go
> +	if url == "" {
may happen in Modify if url is empty

2022-09-28 12:27 UTC, ice-ares commented on news/news_create.go
> +	if url == "" {
ok

2022-09-28 12:29 UTC, ice-laius commented on news/news_get.go
> +	var result []*PersonalNews
done

2022-09-28 12:48 UTC, ice-laius commented on news/news_modify.go
> +		return nil, errors.Wrapf(err, "error inserting newsID %v/userID %v", newsID, userID)
should we increment NEWS views in such case?

2022-09-28 12:51 UTC, ice-laius commented on news/news_get.go
> +		return phrase
if there is an translation error on Get what to do ?

2022-09-28 12:55 UTC, ice-ares commented on news/news_modify.go
> +		return nil, errors.Wrapf(err, "error inserting newsID %v/userID %v", newsID, userID)
nope, views are unique

2022-09-28 12:55 UTC, ice-ares commented on news/news_get.go
> +		return phrase
same thing, return error

2022-09-28 13:17 UTC, ice-myles commented on news/news_modify.go
> +	return &PersonalNews{News: *oldNews}, nil
Yes, sorry. I meant `viewed`.

2022-09-28 13:31 UTC, ice-laius commented on news/news_get.go
> +		return phrase
done

2022-09-28 13:31 UTC, ice-laius commented on news/news_get.go
> +func (r *repository) translate(ctx context.Context, language string, phrase string) string {
done

2022-09-28 13:32 UTC, ice-laius commented on news/news_modify.go
> +		return nil, errors.Wrapf(err, "error inserting newsID %v/userID %v", newsID, userID)
done

2022-09-28 13:36 UTC, ice-laius commented on notifications/DDL.lua
> +                    user_id STRING NOT NULL REFERENCES users(id) ON DELETE CASCADE,
but its      id STRING primary key,

2022-09-28 13:41 UTC, ice-ares commented on notifications/DDL.lua
> +                    user_id STRING NOT NULL REFERENCES users(id) ON DELETE CASCADE,
the pk in users is user_id

2022-09-28 14:50 UTC, ice-laius commented on news/news_get.go
> +		return nil, errors.Wrapf(ErrNotFound, "no news found for type:%v", newsType)
done

2022-09-28 14:52 UTC, ice-laius commented on notifications/DDL.lua
> +                    user_id STRING NOT NULL REFERENCES users(id) ON DELETE CASCADE,
ok I used tables from eskimo due to error in notifications.DDL, fixed
would be use users replication not single db?

2022-09-28 15:16 UTC, ice-laius commented on news/news_modify.go
> +	if err = storage.CheckSQLDMLErr(r.db.PrepareExecute(sql, params)); err != nil {
like this? 		_, err = detectAndParseDuplicateDatabaseError(err)

2022-09-28 15:22 UTC, ice-ares commented on notifications/DDL.lua
> +                    user_id STRING NOT NULL REFERENCES users(id) ON DELETE CASCADE,
?

2022-09-28 15:23 UTC, ice-ares commented on news/news_modify.go
> +	if err = storage.CheckSQLDMLErr(r.db.PrepareExecute(sql, params)); err != nil {
yep

2022-09-30 11:24 UTC, ice-ares commented on cmd/husky-pack/contract.go
> +	ModNews struct {
not needed. use the other one, and embed personal news

2022-09-30 11:29 UTC, ice-ares commented on cmd/husky-pack/news.go
> -				return nil, server.Unexpected(err)
why did u remove this?

2022-09-30 11:34 UTC, ice-ares commented on news/news_modify.go
> +	if err = r.db.UpdateTyped("NEWS", "pk_unnamed_NEWS_1", newsID, arOp, &[]*News{}); err != nil {
`tarantool.StringKey{S:newsID}`

2022-09-30 11:35 UTC, ice-ares commented on news/news_modify.go
> +		return errors.Wrapf(err, "error increasing views count for news ID:%v", newsID)
error updating views by views+1

2022-09-30 11:37 UTC, ice-ares commented on news/news_modify.go
> +		return errors.Wrapf(err, "error adding news ID:%v", newsID)
`error inserting into news viewed by users %#v", tuple`

2022-09-30 11:38 UTC, ice-ares commented on news/news_modify.go
> +		return &PersonalNews{News: *oldNews, Viewed: &viewed}, nil //nolint:nilerr //Duplicate feature
not all errors, only the conflict one

2022-09-30 11:45 UTC, ice-ares commented on news/news_modify.go
> +		return &PersonalNews{News: *oldNews, Viewed: &viewed}, nil //nolint:nilerr //Duplicate feature
also do this before returning: oldNews.sanitizeForUI()

2022-09-30 11:45 UTC, ice-ares commented on news/news_modify.go
> +	return &PersonalNews{News: *oldNews, Viewed: &viewed}, nil
do this before returning: oldNews.sanitizeForUI()

2022-09-30 11:46 UTC, ice-ares commented on news/news_modify.go
> +	if err = r.sendNewsSnapshotSourceMessage(ctx, &Snapshot{News: oldNews.override(news), Before: oldNews}); err != nil {
the result of oldNews.override(news) has to be set for the input news

2022-09-30 11:50 UTC, ice-ares commented on news/news_create.go
> +// Make sure title is correct, meaning translations return something for 'en'
remove this

2022-09-30 11:50 UTC, ice-ares commented on news/news_create.go
> +// Make sure URL is correct and accessible and returns something
remove this

2022-09-30 11:52 UTC, ice-ares requested changes
🧊

2022-09-30 11:53 UTC, ice-ares commented
@ice-nereus make this ready for review if it is ready for review

2022-09-30 14:06 UTC, ice-ares commented on news/news_modify.go
> +			log.Panic("unexpected indexName `%v` for users space", tErr.Data[storage.IndexName])
news space

2022-09-30 14:07 UTC, ice-ares commented on news/news_modify.go
> +		return errors.Wrapf(err, "error updating views by views+1")
add the newsID as well

2022-09-30 14:08 UTC, ice-ares commented on news/news_modify.go
> +		if errors.Is(err, storage.ErrDuplicate) {
never gonna happen. This is for sql methods only.

2022-09-30 14:09 UTC, ice-ares commented on news/news_modify.go
> +		return nil, errors.Wrapf(err, "error inserting newsID:%v to news_viewed_by_users", newsID)
and userID

2022-09-30 14:11 UTC, ice-ares commented on news/news_modify.go
> +	news = oldNews.override(news)
thats not how pointers work.

2022-09-30 14:12 UTC, ice-ares commented on news/news_modify.go
> +		return errors.Wrapf(err, "failed to send user modified news snapshot %#v", news)
put the whole snapshot here

2022-09-30 14:14 UTC, ice-ares commented on news/news_get.go
> +		`SELECT v.created_at IS NOT NULL as viewed,
align it nicely

2022-09-30 14:17 UTC, ice-ares commented on cmd/husky-pack/news.go
> -		// TODO error handle
u have some 400 errors to handle as well

2022-09-30 14:17 UTC, ice-ares commented on cmd/husky-pack/news.go
>  	// TODO validate
validate notification_channels & type

2022-09-30 14:19 UTC, ice-ares commented on cmd/husky-pack/news.go
>  	if true /*TODO if any body field is specified & user is admin*/ {
fix this

2022-09-30 14:20 UTC, ice-ares commented on cmd/husky-pack/news.go
>  	if true /*TODO if any body field is specified & user is admin*/ {
+ validate notification_channels & type

2022-09-30 14:20 UTC, ice-ares commented on cmd/husky-pack/news.go
> -			// TODO error handle
handle all 400 errors

2022-09-30 14:21 UTC, ice-ares commented on cmd/husky-pack/news.go
> -			// TODO error handle
+ 409

2022-09-30 14:22 UTC, ice-ares commented on cmd/husky-pack/news.go
>  	// TODO this should be called only by someone with admin privileges.
fix this

2022-09-30 14:23 UTC, ice-ares requested changes
pay more attention to everything. Make sure each endpoint is production ready

2022-09-30 22:03 UTC, ice-myles commented on news/news_modify.go
> +		return errors.Wrapf(err, "failed to send user modified news snapshot %#v", news)
And something wrong with the error description. `user` is obsolete?

2022-09-30 22:07 UTC, ice-myles commented
@ice-laius please enable auto-merge for this PR.

2022-10-01 10:44 UTC, ice-ares commented on news/news_create.go
> +		return errors.Wrapf(ErrInvalidNewsURL, "news URL: html invalid: %v", url)
Yep

2022-10-03 11:49 UTC, ice-laius commented on news/news_modify.go
> +		if errors.Is(err, storage.ErrDuplicate) {
how to detect duplicate without getting in such case?

2022-10-03 11:57 UTC, ice-ares commented on news/news_modify.go
> +		if errors.Is(err, storage.ErrDuplicate) {
look into storage.CheckDMLError

2022-10-03 12:02 UTC, ice-laius commented on news/news_modify.go
> +		if errors.Is(err, storage.ErrDuplicate) {
found only SQL DML :thinking:

2022-10-03 14:52 UTC, ice-ares commented on cmd/husky-pack/contract.go
> +	wrongTypeErrorCode                = "WRONG_NEWS_TYPE"
those 3 WRONG_* types are not needed. Those are programming errors. Use invalidPropertiesErrorCode

2022-10-03 14:53 UTC, ice-ares commented on cmd/husky-pack/contract.go
> +	userAlreadyPingedErrorCode        = "USER_ALREADY_PINGED"
nolint those 2 to fix the linter

2022-10-03 14:54 UTC, ice-ares commented on cmd/husky-pack/news.go
> -
make format-imports . And fix linting errors

2022-10-03 14:54 UTC, ice-ares commented on cmd/husky-pack/news.go
> +	"k8s.io/utils/strings/slices"
huh?

2022-10-03 14:55 UTC, ice-ares commented on cmd/husky-pack/news.go
>  func (s *service) CreateNews( //nolint:gocritic // .
add funlen in the nolint

2022-10-03 14:55 UTC, ice-ares commented on cmd/husky-pack/news.go
> +	if err := validateCreateUser(req); err != nil {
please pay more attention to what u're committing .

2022-10-03 14:56 UTC, ice-ares requested changes
make the checks pass

2022-10-03 14:57 UTC, ice-ares commented on notifications/contract.go
> +	NotificationChannel             = string
nope

2022-10-03 15:00 UTC, ice-laius commented on cmd/husky-pack/news.go
> +	"k8s.io/utils/strings/slices"
it has to be "golang.org/x/exp/slices"
but missed

2022-10-03 15:03 UTC, ice-ares commented on cmd/husky-pack/news.go
> +			if !slices.Contains(notifications.AllNotificationChannels, notificationChannel) {
we don't import a whole package just cuz you don't want to copy paste 3 lines from eskimo and adapt them.

2022-10-03 15:20 UTC, ice-laius commented on cmd/husky-pack/news.go
> +			if !slices.Contains(notifications.AllNotificationChannels, notificationChannel) {
use double loop here ?

2022-10-03 15:30 UTC, ice-ares commented on cmd/husky-pack/news.go
> +			if !slices.Contains(notifications.AllNotificationChannels, notificationChannel) {
yep

2022-10-03 15:40 UTC, ice-laius commented on cmd/husky-pack/contract.go
> +	wrongTypeErrorCode                = "WRONG_NEWS_TYPE"
wrong role too ?

2022-10-10 12:59 UTC, merged