news total views using materialized view
ice-blockchain/husky pull request #34
Opened 2023-08-01 13:56 UTC by ice-cronus

aggregate views per news entry, not per language

2023-08-02 08:40 UTC, ice-ares requested changes

2023-08-02 08:40 UTC, ice-ares commented on news/DDL.sql
> +CREATE MATERIALIZED VIEW IF NOT EXISTS news_views_by_language (
The whole point was to sum up the views of all languages

2023-08-02 08:40 UTC, ice-ares commented on news/DDL.sql
> +                                SELECT news_id, language, COALESCE(COUNT(*),0) as views
Count result should always be non nil

2023-08-02 08:40 UTC, ice-ares commented on news/news.go
> +	ticker := stdlibtime.NewTicker(stdlibtime.Duration(1+rand.Intn(24)) * stdlibtime.Minute) //nolint:gosec,gomnd // Not an  issue.
10*(1+rand.Intn(10)) * stdlibtime.Second

2023-08-02 08:40 UTC, ice-ares commented on news/news.go
> +	sql := `REFRESH MATERIALIZED VIEW news_views_by_language;`
CONCURRENTLY

2023-08-02 08:40 UTC, ice-ares commented on news/news_get.go
> +				SELECT news_id, SUM(views) as views FROM news_views_by_language GROUP BY news_id
Pointless, as u already have the views by language in the news table

2023-08-02 08:40 UTC, ice-ares commented on news/news_get.go
> +				LEFT JOIN news_views v ON v.news_id = n.id
respect the layout formatting

2023-08-02 08:45 UTC, ice-cronus commented on news/news_get.go
> +				SELECT news_id, SUM(views) as views FROM news_views_by_language GROUP BY news_id
As I understood u're wanna to avoid relying on that views by language calculation from news table. But if we're OK with that - we can redo that materialized view based on news_id only (not per language, and fetch data from news table instead of user_views) and take it from query directly from that view

2023-08-02 09:27 UTC, ice-ares commented on news/news_get.go
> +				SELECT news_id, SUM(views) as views FROM news_views_by_language GROUP BY news_id
U're getting it from news.views either way. So make the view per newsid only and if u need views per language u get it from news.views directly

2023-08-03 10:54 UTC, ice-ares requested changes

2023-08-03 10:54 UTC, ice-ares commented on news/DDL.sql
> +                                 news_id, views
Specify the type, it must be bigint for both

2023-08-03 10:54 UTC, ice-ares commented on news/DDL.sql
> +CREATE UNIQUE INDEX ON news_views (news_id);
Move that into create view ddl

2023-08-03 16:34 UTC, ice-cronus commented on news/DDL.sql
> +                                 news_id, views
Hmm, from [docs specification](https://www.postgresql.org/docs/current/sql-creatematerializedview.html) there are only names without types definitions and constraints. But we can drop them completely and view would use the same names as  in query (we can add `AS news_id` there to match current names)

2023-08-03 16:36 UTC, ice-ares commented on news/DDL.sql
> +                                 news_id, views
No, keep em as is

2023-08-03 17:11 UTC, merged