User notifications
ice-blockchain/husky pull request #4
Opened 2022-10-20 14:42 UTC by ice-laius

2022-10-20 18:51 UTC, ice-myles requested changes

2022-10-20 18:51 UTC, ice-myles commented on cmd/husky-pack/notifications.go
> +		return nil, server.BadRequest(errors.New("empty request"), invalidPropertiesErrorCode)
I can make a mistake, but seems this data should be checked inside the `validateSendNotification` function.

2022-10-20 18:51 UTC, ice-myles commented on cmd/husky-pack/notifications.go
> +		case errors.Is(err, news.ErrNotFound):
Why `news.ErrNotFound`, not `notifications.ErrNotFound`? They are different packages.

2022-10-20 18:51 UTC, ice-myles commented on cmd/husky-pack/notifications.go
> +			case errors.Is(err, news.ErrDuplicate):
I don't see that `PingUser`  from `notifications` package returns `ErrDuplicate` anywhere.

2022-10-20 18:51 UTC, ice-myles commented on cmd/husky-pack/notifications.go
> +		case errors.Is(err, news.ErrDuplicate):
I don't see that `NotifyUser` from `notifications` package returns `ErrDuplicate` anywhere.

2022-10-20 18:51 UTC, ice-myles commented on notifications/contract.go
> +		Channels      *typeChannels
Do we need to use pointer with the map?

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +		return errors.Wrapf(err, "error verifying user %v T1 referral", userID)
```
-"error verifying user %v T1 referral"
+"error verifying userID:%v pinged by T1 referral"
```
?

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +		return errors.Errorf("pinging user should be T1 referral of %v", userID)
```
-"pinging user should be T1 referral of %v"
+"pinging user should be T1 referral of userID:%v"
```
It will describe better this error.

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +	sql := `SELECT COUNT(*) FROM users WHERE referred_by = :requestingUserID AND user_id = :userID`
```
-referred_by = :requestingUserID AND user_id = :userID
+referred_by = :requestingUserId AND user_id = :userId
```
We use IDfor golang code only, not for macros.

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +		return false, errors.Wrapf(err, "failed to get user %v referral %v", userID, requestingUserID)
```
-"failed to get user %v referral %v", userID, requestingUserID
+"failed to get userID:%v requestingUserID:%v", userID, requestingUserID
```
Much more descriptive. Single digits are not clear in th errors.

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +	userEnabledChannels := proc.DeviceMinimal.NotificationSettings["NEWS"] // Should have this in table ?
I assume we have `announcementNotificationDomain` with `TODO` value for such case instead of any other dummy value. Is it right?

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +		return errors.Wrapf(err, "unable to ping user %v", userID)
```suggestion
		return errors.Wrapf(err, "unable to notify userID:%v", userID)
```

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +func (r *repository) deleteNotificationHistory(_ context.Context, sentAt *time.Time, userID users.UserID) error {
Why not to remove context parameter if it is not used?

2022-10-20 18:51 UTC, ice-myles commented on notifications/notify_user.go
> +		mres[ch] = struct{}{}
By the way why do you use map here instead of simple `[]string` if you use key from map only?

2022-10-20 18:53 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +		return nil, server.BadRequest(errors.New("empty request"), invalidPropertiesErrorCode)
its not ready yet
will replace it

2022-10-20 18:55 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +		case errors.Is(err, news.ErrNotFound):
it might be better to remove alias news.ErrNotFound at all and use storage.ErrNotFound
I dont like creating aliases in every package but lets wait what others say..

2022-10-20 18:56 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +			case errors.Is(err, news.ErrDuplicate):
pinguser inserts so why not?

2022-10-20 19:00 UTC, ice-laius commented on notifications/contract.go
> +		Channels      *typeChannels
actually we dont

2022-10-20 19:01 UTC, ice-laius commented on notifications/notify_user.go
> +		return errors.Wrapf(err, "error verifying user %v T1 referral", userID)
but we verify user has such referral not action ))

2022-10-20 19:02 UTC, ice-laius commented on notifications/notify_user.go
> +		return errors.Errorf("pinging user should be T1 referral of %v", userID)
ok

2022-10-20 19:03 UTC, ice-laius commented on notifications/notify_user.go
> +	sql := `SELECT COUNT(*) FROM users WHERE referred_by = :requestingUserID AND user_id = :userID`
ok

2022-10-20 19:05 UTC, ice-laius commented on notifications/notify_user.go
> +		return false, errors.Wrapf(err, "failed to get user %v referral %v", userID, requestingUserID)
ok

2022-10-20 19:09 UTC, ice-laius commented on notifications/notify_user.go
> +func (r *repository) verifyUserPingedByT1Referral(requestingUserID, userID string) (bool, error) {
fixed

2022-10-20 19:10 UTC, ice-laius commented on notifications/notify_user.go
> +		return errors.Wrapf(ErrNotFound, "no devices registered for user %v", userID)
ok

2022-10-20 19:15 UTC, ice-laius commented on notifications/notify_user.go
> +	userEnabledChannels := proc.DeviceMinimal.NotificationSettings["NEWS"] // Should have this in table ?
perhaps, I have to idea would we use single domain or multiple.. looks like we have to wait..

2022-10-20 19:17 UTC, ice-laius commented on notifications/notify_user.go
> +		return errors.Wrapf(err, "unable to ping user %v", userID)
ping is a subset of notifications..

2022-10-20 19:18 UTC, ice-laius commented on notifications/notify_user.go
> +func (r *repository) deleteNotificationHistory(_ context.Context, sentAt *time.Time, userID users.UserID) error {
ok

2022-10-20 19:21 UTC, ice-laius commented on notifications/notify_user.go
> +		mres[ch] = struct{}{}
because map(actually set here) is O(log n) but unsorted array is O(n) and we use it many times

2022-10-20 19:53 UTC, ice-myles commented on cmd/husky-pack/notifications.go
> +			case errors.Is(err, news.ErrDuplicate):
Ah, yeah, right, insert operation can return this code and we shouldn't add this code explicitely. Sorry.

2022-10-21 15:12 UTC, ice-myles requested changes

2022-10-24 09:20 UTC, ice-laius commented on notifications/notify_user.go
> +	return nil
ok

2022-10-24 09:21 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +		if len(req.Data.InApp.Description) == 0 {
ok

2022-10-24 09:21 UTC, ice-laius commented on notifications/notify_user.go
> +			FROM device_settings WHERE disable_all_notifications = false AND user_id = :user_id ORDER BY updated_at DESC`
ok

2022-10-24 09:22 UTC, ice-laius commented on notifications/notify_user.go
> +	if !*userEnabledChannels.Push || notification == nil || (!proc.Channels.has("all") && !proc.Channels.has("inApp")) {
yes

2022-10-24 09:25 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +		return nil, server.BadRequest(errors.New("empty request"), invalidPropertiesErrorCode)
done

2022-10-24 09:25 UTC, ice-laius commented on cmd/husky-pack/notifications.go
> +		case errors.Is(err, news.ErrNotFound):
done

2023-01-26 10:22 UTC, ice-myles commented
Continued at #8, so this PR can be closed.

2023-01-26 10:22 UTC, closed without merging