Scheduled notifications and announcements
ice-blockchain/husky pull request #41
Opened 2024-06-04 12:09 UTC by ice-myles

Changed the translation files format (removed dir and files from dir were moved to 1 file for each notification type).

2024-06-04 12:51 UTC, ice-ares commented on application.yaml
> +  host: localhost:8443
port mismatch here

2024-06-06 13:43 UTC, ice-ares requested changes

2024-06-06 13:43 UTC, ice-ares commented on cmd/husky-bark/api/docs.go
> +
Why donu need swagger for it? Check how miner cmd is in that regard

2024-06-06 13:43 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +						ON CONFLICT DO NOTHING
If u're inserting before sending, they u need to conflict if duplication

2024-06-06 13:43 UTC, ice-ares commented on notifications/contract.go
> +	MiningNotActiveNotificationType     NotificationType = "mining_not_active"
Whats the difference ?

2024-06-06 13:43 UTC, ice-ares commented on notifications/contract.go
> +	miningSource struct {
miningSessionSource

2024-06-06 13:43 UTC, ice-ares commented on notifications/notification_invite_friend.go
> +		miningSessionDuration = 24 * stdlibtime.Hour
This is no longer the case, cuz the mining sesion duration can be specific per user and it can be up to 48h. So i suggest you compare the end of the mining session. Check my changes in freezer about that. You can add extra info in the mining session message thats being sent if u need to

2024-06-06 13:43 UTC, ice-ares commented on notifications/notification_type_mining.go
> +			ON CONFLICT(user_id, uniqueness, notification_type, notification_channel, notification_channel_value)
Think of duplicate message processing, cuz the delivery guarantee is atleast once. So u need to make sure that if u process the same message twice, its idempotent and u dont send the same push twice

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +		mb:                       messagebroker.MustConnect(context.Background(), applicationYamlKey), //nolint:contextcheck // .
Why do u need this?

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +	ticker := stdlibtime.NewTicker(duration)
Bad idea. Try to add it every minute. And only the one at 10 am on every monday morning succeeds

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +func getData(jsonMap *users.JSON) map[string]string {
U can use type inference.

getData[T any](jsonVal *users.JSON) *T

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +			LIMIT %v;`, s.cfg.Scheduler.Workers, workerNumber, s.cfg.Scheduler.BatchSize)
Order by Scheduled_for asc

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +				WHERE MOD(i, %v) = %v
U need composite index on that expression and scheduled_for

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
sn.i is enough

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +				LIMIT %v`,
Order by scheduled_for asc

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +				      AND scheduled_for <= $1
Same index here as well

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +func (s *Scheduler) insertSentNotifications(ctx context.Context, now *time.Time, notifications []*pushNotification) error {
markScheduledNotificationAsSent

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +func (s *Scheduler) deleteScheduledAnnouncements(
markScheduledAnnouncementAsSent

2024-06-06 13:43 UTC, ice-ares commented on notifications/scheduler.go
> +		announcements, err = s.fetchScheduledAnnouncements(ctx, now, workerNumber)
Lets move announcements to a separate goroutine pipeline; to make notifications and announcements be processed independently

2024-06-06 13:56 UTC, ice-myles commented on notifications/contract.go
> +	MiningNotActiveNotificationType     NotificationType = "mining_not_active"
Different types of the notifications. Expired - after mining has just expired. Not active - after some days left. If they can be 1 with some parameter - I will remove obsolete.

2024-06-06 14:11 UTC, ice-ares commented on notifications/contract.go
> +	MiningNotActiveNotificationType     NotificationType = "mining_not_active"
Just expired = 0 days passed, right?

2024-06-10 18:24 UTC, ice-myles commented on notifications/notification_invite_friend.go
> +		miningSessionDuration = 24 * stdlibtime.Hour
Actually SoloEndedAt can have the max mining session value (> 24 hours), so for most cases it is enough to add notifications for 1d, 7d, etc after mining expired. Just ResettableStartingAt and WarnAboutExpirationStartingAt fields should be added here to make notifications for these time points.

2024-06-10 18:24 UTC, ice-myles commented on notifications/scheduler.go
> +			LIMIT %v;`, s.cfg.Scheduler.Workers, workerNumber, s.cfg.Scheduler.BatchSize)
By MOD(i, ...) and scheduler_for then as it is indexed.

2024-06-10 18:25 UTC, ice-myles commented on notifications/scheduler.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
Not enough due to aggregation function to take push notification tokens.

2024-06-10 20:42 UTC, ice-ares commented on notifications/scheduler.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
Then use just ids

2024-06-11 12:31 UTC, ice-myles commented on notifications/notification_type_mining.go
> +			ON CONFLICT(user_id, uniqueness, notification_type, notification_channel, notification_channel_value)
How is that possible now when we don't save the `sent_notifications` first, while processing them, and removing the values from available notifications only in the end of processing, when now we just do insert-delete by atomic operation in the end.

Theoretically if we don't start the 2nd+ instance of husky-bark, we will not process the same message twice as each MOD(I, workerCount) value is only per 1 worker.

2024-06-11 13:14 UTC, ice-ares reviewed
Also check each notification and see how it would work on staging, how frequent, etc

2024-06-11 13:14 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +			Uniqueness:               fmt.Sprintf("%v_%v_%v", WeeklyStatsNotificationType, language, nextTime.UnixNano()),
put the date formatted as dd-mm-yyyy instead of unix nano

2024-06-11 13:14 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +			Uniqueness:               fmt.Sprintf("%v_%v_%v", WeeklyStatsNotificationType, language, nextTime.UnixNano()),
Make it day based if its prod, and minute based if its development

2024-06-11 13:14 UTC, ice-ares commented on notifications/notification_invite_friend.go
> +			ScheduledFor:             time.New(us.CreatedAt.Add(dayDuration / 24)),
Lets make days be minutes on staging

2024-06-11 13:14 UTC, ice-ares commented on notifications/notification_invite_friend.go
> +			Uniqueness:               fmt.Sprintf("%v_%v", us.ID, time.New(us.CreatedAt.Add(dayDuration/24)).UnixNano()),
Stop doing nanos as uniqueness, thats anything but unique. Put some usecases there, ie, first notif, second, etc

2024-06-11 13:14 UTC, ice-ares commented on notifications/notification_invite_friend.go
> +			NotificationChannelValue: us.ID,
this should be the token

2024-06-11 13:14 UTC, ice-ares commented on notifications/notifications.go
> +	ddlWorkersParam := fmt.Sprintf(ddl, cfg.Scheduler.Workers)
Lets hardcode 10

2024-06-11 13:14 UTC, ice-ares commented on notifications/scheduler.go
> +	wg.Add(2 * int(cfg.Scheduler.Workers)) //nolint:gomnd,mnd // .
Hardcode workers and batch size. Find the best values

2024-06-11 13:14 UTC, ice-ares commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
Why do this again?

2024-06-11 13:14 UTC, ice-ares commented on notifications/scheduler_announcements.go
> +		imageURLAnnouncement        = s.pictureClient.DownloadURL("assets/push-notifications/batch-announcement.png")
Whats this?

2024-06-11 13:14 UTC, ice-ares commented on notifications/scheduler_notifications.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
Group by sn.i, u.user_id

2024-06-11 13:14 UTC, ice-ares commented on notifications/scheduler_notifications.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
if that fails to run, add u.user_id in columns list

2024-06-11 13:29 UTC, ice-myles commented on notifications/notification_invite_friend.go
> +			NotificationChannelValue: us.ID,
No, it can't be the token because these notifications are created on user creation, when user still can not have any device metadata information. Tokens must be taken only when notification is processed, especially due to user can have several tokens till that moment.

2024-06-11 13:30 UTC, ice-myles commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
This log.Error only for cases when no ErrDuplicate: problems with database connection, etc.

2024-06-11 13:32 UTC, ice-myles commented on notifications/scheduler_announcements.go
> +		imageURLAnnouncement        = s.pictureClient.DownloadURL("assets/push-notifications/batch-announcement.png")
Some image for the announcements. How can they be customized per announcement? For news for example we used the image from article, but here no any specific image.

2024-06-11 13:34 UTC, ice-ares commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
Yea, but u retry in 1 min anyway, so whats the point?

2024-06-11 13:35 UTC, ice-ares commented on notifications/scheduler_announcements.go
> +		imageURLAnnouncement        = s.pictureClient.DownloadURL("assets/push-notifications/batch-announcement.png")
Then u need to tenant-ize em

2024-06-11 13:41 UTC, ice-myles commented on notifications/scheduler_announcements.go
> +		imageURLAnnouncement        = s.pictureClient.DownloadURL("assets/push-notifications/batch-announcement.png")
They will be tenantized by config:
```
wintr/multimedia/picture:
    urlDownload: https://[tenantA,B,C,...]-[staging, production].b-cdn.net
```

2024-06-11 13:42 UTC, ice-myles commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
But you [suggested](https://github.com/ice-blockchain/husky/pull/41#discussion_r1629530534) to do it per 1 minute.

2024-06-11 13:54 UTC, ice-myles commented on notifications/notification_invite_friend.go
> +			ScheduledFor:             time.New(us.CreatedAt.Add(dayDuration / 24)),
They are already minutes everywhere for staging, but in this case 1 minute / 24, will do it better to have 1 minute to have better delay.

2024-06-11 13:56 UTC, ice-ares commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
I mean the ticker will retry it in 1 min anyway

2024-06-11 14:00 UTC, ice-myles commented on notifications/scheduler_notifications.go
> +				GROUP BY sn.i, sn.scheduled_at, sn.scheduled_for, sn.data, sn.language, sn.user_id, sn.uniqueness, sn.notification_type,
Unfortunately it requires to have all non-aggregated fields, no matter to add u.user_id or not.

2024-06-11 14:14 UTC, ice-myles commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
10 AM Monday week 1 -> weekly_stats were sent - > this ticker handler will add message for the next 10 AM monday morning for the next week 2.
11.XX AM Monday -> ErrDuplicate
12.XX AM Monday -> ErrDuplicate
...
10 AM Monday week 2 -> weekly_stats were sent - > this ticker handler will add message for the next 10 AM monday morning for the next week 3.
etc

Do you think it need to change the retry time on success?

2024-06-11 14:22 UTC, ice-ares commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
Yea, i mean that u dont have to add that call twice, cuz it will succeed the next minute, when the ticker runs again, right?

2024-06-11 14:44 UTC, ice-myles commented on notifications/announcement_weekly_stats.go
> +			Uniqueness:               fmt.Sprintf("%v_%v_%v", WeeklyStatsNotificationType, language, nextTime.UnixNano()),
staging:
**invite_friend_1h**  - createdAt + 1 minute
**invite_friend_7d** - createdAt + 7 minutes

**mining_ending_soon** - value "warn" from freezer 
**mining_extend** - value "ResetAt" from freezer 
**mining_expired_0d** - miningSessionSoloEndedAt
**mining_expired_1d** - miningSessionSoloEndedAt + 1 minute
**mining_expired_7d** - miningSessionSoloEndedAt + 7 minutes
**mining_expired_14d** - miningSessionSoloEndedAt + 14 minutes
**mining_expired_30d** - miningSessionSoloEndedAt + 30 minutes

**socials_1d** - createdAt + 1 minute
**socials_2d** - createdAt + 2 minute
**socials_xx** - createdAt + XX minutes

weekly_stats - each minute.

2024-06-11 15:02 UTC, ice-myles commented on notifications/scheduler.go
> +				log.Error(errors.Wrap(s.addScheduledWeeklyStatsAnnouncement(reqCtx), "failed to addScheduledWeeklyStatsAnnouncement"))
Ahh, this is stupid error, just need to log.Error(err, ...) instead of the second addXXX call.

2024-06-11 15:31 UTC, ice-myles commented on notifications/scheduler.go
> +	wg.Add(2 * int(cfg.Scheduler.Workers)) //nolint:gomnd,mnd // .
```The default quota of 600k messages per minute covers over 99% of FCM developers while protecting the stability of the system and minimizing the impact of spiky projects.```
We have 10 notification workers, 10 announcement workers. 
600k/20 = 30k per worker per minute. If we take into account that we will spend ~1 sec per batch, then it's 500 per batch.

But when tested migrated push notification API, 250 per batch showed more stable behaviour. So, 250 per batch I expect.

2024-06-11 15:38 UTC, ice-ares commented on notifications/scheduler.go
> +	wg.Add(2 * int(cfg.Scheduler.Workers)) //nolint:gomnd,mnd // .
Ok, put the optimal batch size end to end

2024-06-12 12:46 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +		nextTimeFormatted = nextTime.Format("2006-01-01 01:00")
that's hour format, not minute

2024-06-12 12:46 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +		nextTimeFormatted = nextTime.Format("2006-01-01 01:00")
just use the stdlib formats

2024-06-12 12:47 UTC, ice-ares commented on notifications/announcement_weekly_stats.go
> +func nextTimeMatch(now *time.Time, weekday stdlibtime.Weekday, hour, minute int) *time.Time {
add unit tests for this cuz it seems complex

2024-06-12 12:54 UTC, ice-ares commented on notifications/notification_type_mining.go
> +			multierror.Append(mErr, errors.Wrapf(m.insertScheduledNotifications(ctx, old), "can't rollback scheduled notifications for:%v", message)) //nolint:lll,errcheck // .
mErr = 

cuz Append doesn't mutate the input

2024-06-14 16:37 UTC, merged