User contacts improvement
ice-blockchain/husky pull request #8
Opened 2023-04-22 11:45 UTC by ice-myles

Contacts table processor was added to handle contact referrals from contacts-table topic. Contact notification was changed accordingly to send notifications about new contact to user.

Related to [eskimo PR#6](https://github.com/ice-blockchain/eskimo/pull/6)

2023-05-10 11:23 UTC, ice-ares requested changes

2023-05-10 11:23 UTC, ice-ares commented on notifications/contract.go
> +	contactsTableSource struct {
agendaContacts

2023-05-10 11:23 UTC, ice-ares commented on notifications/notification_type_new_contact.go
> +func (r *repository) sendNewContactNotification(ctx context.Context, contact *users.Contact) error { //nolint:funlen,gocognit // .
AgendaContact

2023-05-10 11:23 UTC, ice-ares commented on notifications/notification_type_new_contact.go
> +						WHERE u.user_id = $1
Do you send  a message for each (userId,contactUserId) pair u find in db, from eskimo?

Meaning contactUserId is the same, but userId is different, cuz there could be multiple users that have that contact in their agenda, not just the user that generated the request in eskimo

2023-05-10 11:54 UTC, ice-myles commented on notifications/notification_type_new_contact.go
> +						WHERE u.user_id = $1
Why userId should be different?
User has agenda phone number hashes, we send modify request for this user with `phoneNumberHash1,phoneNumberHash2,phoneNumberHash3`, then we should find the users that has these phone number hashes, then send {userID, user1::phoneNumberHash1}, {userID, user2::phoneNumberHash2}, {userID, user3::phoneNumberHash3} pairs only (::phoneNumberHash I use is to show the correspondence between userID and phonehNumberHash).

2023-05-10 14:10 UTC, ice-ares commented on notifications/notification_type_new_contact.go
> +						WHERE u.user_id = $1
Then u should change it to detect all userId values for that contactUserId, cuz we need to detect all the users that have that other user in their contacts, not just the one requesting it

2023-05-29 23:59 UTC, ice-ares requested changes

2023-05-29 23:59 UTC, ice-ares commented on news/DDL.sql
> +                    views                 BIGINT NOT NULL DEFAULT 0,
Move this after last timestamp

2023-05-29 23:59 UTC, ice-ares commented on news/DDL.sql
> +CREATE INDEX IF NOT EXISTS most_recent_news_lookup_ix ON news (language, type, created_at);
Add DESC to created at

2023-05-29 23:59 UTC, ice-ares commented on news/news_create.go
> -		return errors.Wrapf(detectAndParseDuplicateDatabaseError(err), "failed to insert news %#v", news)
U dont need this?

2023-05-29 23:59 UTC, ice-ares commented on news/news_modify.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-29 23:59 UTC, ice-ares commented on notifications/email_notifications.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-29 23:59 UTC, ice-ares commented on notifications/inapp_notifications.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-29 23:59 UTC, ice-ares commented on notifications/inapp_notifications.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-29 23:59 UTC, ice-ares commented on notifications/push_notifications.go
> +	err := storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-29 23:59 UTC, ice-ares commented on notifications/push_notifications.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same pattern as before

2023-05-30 10:01 UTC, merged